name: Docker

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Configs
              uses: actions/checkout@v3
            - name: Build image
              run: docker build . --file Dockerfile --tag url-shortener
            - name: Log into registry
              run: echo "${{ secrets.DOCKER_ACCESSTOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            - name: Push image
              run: |
                  IMAGE_ID=LEDBrain/url-shortener
                  IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
                  VERSION=latest
                  echo IMAGE_ID=$IMAGE_ID
                  echo VERSION=$VERSION
                  docker tag url-shortener $IMAGE_ID:$VERSION
                  docker push $IMAGE_ID:$VERSION
